<?xml version="1.0" encoding="utf-8"?><Database Name="Sample" Class="SampleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-S15FSJL;Initial Catalog=Sample;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SampleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DepartmentsLINQ" Member="DepartmentsLINQ">
    <Type Name="DepartmentsLINQ">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DepartmentsLINQ_EmployeesLINQ" Member="EmployeesLINQ" ThisKey="ID" OtherKey="DepartmentId" Type="EmployeesLINQ" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeesLINQ" Member="EmployeesLINQ">
    <Type Name="EmployeesLINQ">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DepartmentsLINQ_EmployeesLINQ" Member="DepartmentsLINQ" ThisKey="DepartmentId" OtherKey="ID" Type="DepartmentsLINQ" IsForeignKey="true" />
    </Type>
  </Table>
</Database>